[build]
  command = "cd ../.. && pnpm turbo run build --filter=frontend"
  publish = "dist/client"
  
[functions]
  directory = ".netlify/v1/functions"
  node_bundler = "esbuild"

[dev]
  command = "pnpm dev"
  targetPort = 3000
  port = 8888

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200